name: 🌟 Feature Request
description: Request a new feature to improve the project
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you continue:
        - Search through the [issues](https://github.com/Crazy-Unicooorn/crazy-guessr/issues?q=is%3Aissue) and [pull requests](https://github.com/Crazy-Unicooorn/crazy-guessr/pulls?q=is%3Apr) for what you're about to ask for.
        - If you want to discuss a topic at length, you can use the [discussion](https://github.com/Crazy-Unicooorn/crazy-guessr/discussions) section
        - Please open one feature request per feature. You can always link between issues if they are related.

  - type: textarea
    id: description
    attributes:
      label: 📝 Provide a description of the new feature
      description: What is the expected behavior of the proposed feature? What is the scenario where this would be used?
      placeholder: I'd like to see…
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🧩 Context
      description: If some context is required, describe it here
      placeholder: When I do… I find it difficult to… because…
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: ➕ Additional Information
      description: Give us some additional information on the feature request like links, screenshots, etc.
      placeholder: Here is a screenshot of…

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Please check the following before submitting your feature request
      options:
        - label: I have searched through the existing issues and pull requests and confirmed that this is not a duplicate
          required: true
        - label: I have opened one feature request per feature. In case of multiple feature requests I will open a new issue for each
          required: true

  - type: markdown
    attributes:
      value: If you'd like to see this feature implemented, add a 👍 reaction to this post.
