name: Feature Request
description: Request a new feature for the project
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: input
    id: feature-request-title
    attributes:
      label: Feature Request Title
      description: A clear and concise title for the feature request
      placeholder: Add a title for the feature request
      required: true
  - type: markdown
    attributes:
      value: |
        ### Feature Request
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
        
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.
        
        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.
        
        **Additional context**
        Add any other context or screenshots about the feature request here.
      required: true