import ImageMagnifier from "../../common/ImageMagnifier";
import Separator from "../../common/Separator";
import { Card, Head, Tip } from "../../common/TipsBuilder";
import TrainingModal from "../../common/TrainingModal";
import countryCallingCodeMap from "../../../assets/img/world/Country_calling_codes_map.png";

function WorldCallingCodes() {
  const CallingCodes: Card[] = [
    { front: "1", back: "Canada & U.S.A." },
    { front: "1-340", back: "U.S. Virgin Islands" },
    { front: "1-441", back: "Bermuda" },
    { front: "1-670", back: "Northern Mariana Islands" },
    { front: "1-671", back: "Guam" },
    { front: "1-787", back: "Puerto Rico" },
    { front: "1-684", back: "American Samoa" },
    { front: "1-809", back: "Dominican Republic" },
    { front: "1-829", back: "Dominican Republic" },
    { front: "1-849", back: "Dominican Republic" },
    { front: "1-930", back: "Puerto Rico" },
    { front: "20", back: "Egypt" },
    { front: "216", back: "Tunisia" },
    { front: "221", back: "Senegal" },
    { front: "223", back: "Mali" },
    { front: "233", back: "Ghana" },
    { front: "234", back: "Nigeria" },
    { front: "246", back: "British Indian Ocean Territory" },
    { front: "250", back: "Rwanda" },
    { front: "254", back: "Kenya" },
    { front: "255", back: "Tanzania" },
    { front: "256", back: "Uganda" },
    { front: "261", back: "Madagascar" },
    { front: "262", back: "Reunion" },
    { front: "264", back: "Namibia" },
    { front: "266", back: "Lesotho" },
    { front: "267", back: "Botswana" },
    { front: "268", back: "Eswatini / Swaziland" },
    { front: "298", back: "Faroe Islands" },
    { front: "299", back: "Greenland" },
    { front: "27", back: "South Africa" },
    { front: "30", back: "Greece" },
    { front: "31", back: "Netherlands" },
    { front: "32", back: "Belgium" },
    { front: "33", back: "France" },
    { front: "34", back: "Spain" },
    { front: "350", back: "Gibraltar" },
    { front: "351", back: "Portugal" },
    { front: "352", back: "Luxembourg" },
    { front: "353", back: "Ireland" },
    { front: "354", back: "Iceland" },
    { front: "355", back: "Albania" },
    { front: "356", back: "Malta" },
    { front: "358", back: "Finland" },
    { front: "359", back: "Bulgaria" },
    { front: "36", back: "Hungary" },
    { front: "370", back: "Lithuania" },
    { front: "371", back: "Latvia" },
    { front: "372", back: "Estonia" },
    { front: "375", back: "Belarus" },
    { front: "376", back: "Andorra" },
    { front: "377", back: "Monaco" },
    { front: "378", back: "San Marino" },
    { front: "380", back: "Ukraine" },
    { front: "381", back: "Serbia" },
    { front: "382", back: "Montenegro" },
    { front: "385", back: "Croatia" },
    { front: "386", back: "Slovenia" },
    { front: "389", back: "North Macedonia" },
    { front: "39", back: "Italy" },
    { front: "40", back: "Romania" },
    { front: "41", back: "Switzerland" },
    { front: "420", back: "Czech Republic" },
    { front: "421", back: "Slovakia" },
    { front: "43", back: "Austria" },
    { front: "44", back: "United Kingdom" },
    { front: "44-1534", back: "Jersey" },
    { front: "44-1624", back: "Isle of Man" },
    { front: "44-7524", back: "Isle of Man" },
    { front: "44-7624", back: "Isle of Man" },
    { front: "44-7924", back: "Isle of Man" },
    { front: "45", back: "Denmark" },
    { front: "46", back: "Sweden" },
    { front: "47", back: "Norway" },
    { front: "47-49", back: "Svalbard" },
    { front: "48", back: "Poland" },
    { front: "49", back: "Germany" },
    { front: "500", back: "Falkland Islands & South Georgia and the South Sandwich Islands" },
    { front: "502", back: "Guatemala" },
    { front: "506", back: "Costa Rica" },
    { front: "507", back: "Panama" },
    { front: "508", back: "Saint Pierre and Miquelon" },
    { front: "51", back: "Peru" },
    { front: "52", back: "Mexico" },
    { front: "54", back: "Argentina" },
    { front: "55", back: "Brazil" },
    { front: "56", back: "Chile" },
    { front: "57", back: "Colombia" },
    { front: "591", back: "Bolivia" },
    { front: "593", back: "Ecuador" },
    { front: "596", back: "Martinique" },
    { front: "598", back: "Uruguay" },
    { front: "599-9", back: "Curaçao" },
    { front: "60", back: "Malaysia" },
    { front: "61", back: "Australia" },
    { front: "62", back: "Indonesia" },
    { front: "63", back: "Philippines" },
    { front: "64", back: "New Zealand & Pitcairn Islands" },
    // { front: "64", back: "Pitcairn Islands" },
    { front: "65", back: "Singapore" },
    { front: "66", back: "Thailand" },
    { front: "678", back: "Vanuatu" },
    { front: "7", back: "Russia" },
    { front: "81", back: "Japan" },
    { front: "82", back: "South Korea" },
    { front: "84", back: "Vietnam" },
    { front: "852", back: "Hong Kong" },
    { front: "853", back: "Macau" },
    { front: "855", back: "Cambodia" },
    { front: "856", back: "Laos" },
    { front: "86", back: "China" },
    { front: "880", back: "Bangladesh" },
    { front: "886", back: "Taiwan" },
    { front: "90", back: "Turkey" },
    { front: "91", back: "India" },
    { front: "92", back: "Pakistan" },
    { front: "93", back: "Afghanistan" },
    { front: "94", back: "Sri Lanka" },
    { front: "961", back: "Lebanon" },
    { front: "962", back: "Jordan" },
    { front: "963", back: "Syria" },
    { front: "964", back: "Iraq" },
    { front: "971", back: "United Arab Emirates" },
    { front: "972", back: "Israel" },
    { front: "974", back: "Qatar" },
    { front: "975", back: "Bhutan" },
    { front: "976", back: "Mongolia" },
    { front: "977", back: "Nepal" },
    { front: "996", back: "Kyrgyzstan" },
    // { front: "", back: "Antarctica" },
    // { front: "500", back: "South Georgia and the South Sandwich Islands" },
    // { front: "", back: "United States" },
  ];

  const FinalCallingCodes = CallingCodes.map((card) => ({
    ...card,
    front: `+${card.front}`,
  }));

  return (
    <Tip>
      <Head>
        <h1 className="singleline-text">Calling Codes</h1>
        <Separator />
        <TrainingModal cards={FinalCallingCodes} />
      </Head>
      <ImageMagnifier
        src={countryCallingCodeMap}
        alt="World map of calling codes"
        style={{ backgroundColor: "#ecfbff" }}
      />
    </Tip>
  );
}

export default WorldCallingCodes;
