import generateRandomCard from "../../common/Logic/GenerateRandomCard";
import Separator from "../../common/Separator";
import { Card, Head, Tip } from "../../common/TipsBuilder";
import TrainingModal from "../../common/TrainingModal";
import nativeCountryNames from "../../../assets/img/world/native_country_names.webp";

function LocalCountryNamesCard() {
  const localCountryNames: Card = {
    // Andorra: "Andorra",
    "الإمارات العربيّة المتّحدة": "United Arab Emirates",
    افغانستان: "Afghanistan",
    Shqipëria: "Albania",
    // aq: "Antarctica",
    // ar: "Argentina",
    // as: "American Samoa",
    Österreich: "Austria",
    // au: "Australia",
    বাংলাদেশ: "Bangladesh",
    België: "Belgium (Dutch)",
    Belgique: "Belgium (French)",
    Belgien: "Belgium (German)",
    България: "Bulgaria",
    // bm: "Bermuda",
    Wuliwya: "Bolivia (Aymara)",
    Volívia: "Bolivia (Guarani)",
    Buliwya: "Bolivia (Quechua)",
    // br: "Brazil",
    "Druk Yul": "Bhutan",
    "འབྲུག་ཡུལ": "Bhutan",
    // bw: "Botswana",
    Беларусь: "Belarus",
    // ca: "Canada",
    Suisse: "Switzerland (French)",
    Schweiz: "Switzerland (German)",
    Svizzera: "Switzerland (Italian)",
    Svizra: "Switzerland (Romansh)",
    // cl: "Chile",
    Zhōngguó: "China",
    中国: "China",
    // co: "Colombia",
    // cr: "Costa Rica",
    // cw: "Curaçao",
    Česko: "Czech Republic",
    Deutschland: "Germany",
    // dk: "Denmark",
    "República Dominicana": "Dominican Republic",
    // ec: "Ecuador",
    Eesti: "Estonia",
    Misr: "Egypt",
    مصر: "Egypt",
    España: "Spain",
    Espanya: "Spain (Catalan)",
    Espainia: "Spain (Basque)",
    Suomi: "Finland",
    // fk: "Falkland Islands",
    // fo: "Faroe Islands",
    // fr: "France",
    "Y Deyrnas Unedig": "United Kingdom (Welsh)",
    "Rìoghachd Aonaichte": "United Kingdom (Scottish Gaelic)",
    "Ríocht Aontaithe": "United Kingdom (Irish)",
    Gaana: "Ghana (Akan)",
    Gana: "Ghana (Ewe / Twi)",
    // gi: "Gibraltar",
    // gl: "Greenland",
    Ελλάς: "Greece",
    // gs: "South Georgia and the South Sandwich Islands",
    // gt: "Guatemala",
    // gu: "Guam",
    香港: "Hong Kong",
    Hrvatska: "Croatia",
    Magyarország: "Hungary",
    // id: "Indonesia",
    Éire: "Ireland (Irish)",
    إسرائيل: "Israel (Arabic)",
    ישראל: "Israel (Hebrew)",
    // im: "Isle of Man",
    ভাৰত: "India (Assamese)",
    ভারত: "India (Bengali)",
    ભારત: "India (Gujarati)",
    भारत: "India (Hindi / Kannada / Malayalam / Marthi / Nepalese)",
    ಭಾರತ: "India (Konkai)",
    ഭാരതം: "India (Malayalam)",
    ଭାରତ: "India (Oriya)",
    ਭਾਰਤ: "India (Punjabi)",
    भारतम्: "India (Sanskrit)",
    பாரதம்: "India (Tamil)",
    "భారత దేశం": "India (Telugu)",
    // io: "British Indian Ocean Territory",
    العراق: "Iraq",
    Ísland: "Iceland",
    Italia: "Italy",
    // je: "Jersey",
    الأردن: "Jordan",
    日本: "Japan",
    // ke: "Kenya",
    Кыргызстан: "Kyrgyzstan (Kyrgyz)",
    Киргизия: "Kyrgyzstan (Russian)",
    កម្ពុជា: "Cambodia",
    한국: "South Korea",
    // 남한: "South Korea",
    ປະເທດລາວ: "Laos",
    لبنان: "Lebanon (Arabic)",
    Liban: "Lebanon (French)",
    "ශ්‍රී ලංකාව": "Sri Lanka (Sinhala)",
    இலங்கை: "Sri Lanka (Tamil)",
    // ls: "Lesotho",
    Lietuva: "Lithuania",
    Lëtezebuerg: "Luxembourg",
    Latvija: "Latvia",
    Múnegu: "Monaco (Monegasque)",
    Madagasikara: "Madagascar (Malagasy)",
    Crna: "Montenegro",
    Gora: "Montenegro",
    Црна: "Montenegro",
    Гора: "Montenegro",
    "Северна Македонија": "North Macedonia",
    // ml: "Mali",
    "Монгол Улс": "Mongolia",
    // mo: "Macao",
    // mp: "Northern Mariana Islands",
    // mq: "Martinique",
    // mt: "Malta",
    Mēxihco: "Mexico (Nahuatl)",
    马来西亚: "Malaysia (Mandarin Chinese)",
    மலேசியா: "Malaysia (Tamil)",
    // na: "Namibia",
    Nijeriya: "Nigeria (Hausa)",
    Naigeria: "Nigeria (Igbo)",
    Nàìjíríà: "Nigeria (Yoruba)",
    Nederland: "Netherlands (Dutch)",
    Nederlân: "Netherlands (Frisian)",
    Norge: "Norway",
    नेपाल: "Nepal",
    Aotearoa: "New Zealand (Maori)",
    // pa: "Panama",
    Piruw: "Peru (Aymara)",
    Pilipinas: "Philippines (Filipino)",
    پاکستان: "Pakistan (Urdu)",
    Polska: "Poland",
    // pm: "Saint Pierre and Miquelon",
    // pn: "Pitcairn",
    // pr: "Puerto Rico",
    // pt: "Portugal",
    قطر: "Qatar",
    // re: "Reunion",
    // ro: "Romania",
    Србија: "Serbia",
    Россия: "Russia",
    // rw: "Rwanda",
    Sverige: "Sweden",
    Singapura: "Singapore (Malay)",
    新加坡: "Singapore (Mandarin Chinese)",
    சிங்கப்பூர்: "Singapore (Tamil)",
    Slovenija: "Slovenia",
    Slovensko: "Slovakia",
    // sm: "San Marino",
    Sénégal: "Senegal",
    سورية: "Syria",
    // sz: "Eswatini / Swaziland",
    เมืองไทย: "Thailand (Mueang Thai)",
    ประเทศไทย: "Thailand (Prathet Thai)",
    ราชอาณาจักรไทย: "Thailand (Ratcha-anachak Thai)",
    تونس: "Tunisia",
    Türkiye: "Turkey",
    臺灣: "Taiwan (Traditional Chinese)",
    台灣: "Taiwan (Simplified Chinese)",
    // tz: "Tanzania",
    Україна: "Ukraine",
    // ug: "Uganda",
    // us: "United States",
    // uy: "Uruguay",
    // vi: "U.S. Virgin Islands",
    "Việt Nam": "Vietnam",
    // vu: "Vanuatu",
    // xv: "Svalbard",
    "Suid-Afrika": "South Africa (Afrikaans)",
    "iNingizimu Afrika": "South Africa (Zulu)",
    "uMzantsi Afrika": "South Africa (Xhosa)",
    "Afrika-Borwa": "South Africa (Northern Sotho)",
  };

  return generateRandomCard(localCountryNames);
}

function LocalCountryNames() {
  return (
    <Tip>
      <Head>
        <h1 className="singleline-text">Local Country Names</h1>
        <Separator />
        <TrainingModal cardSource={LocalCountryNamesCard} />
      </Head>
      <p>
        Names of countries in their own languages. Recall Training only includes names that are different than the
        English ones. If you think some information is irrelevant for GeoGuessr, or if you spot any error please report
        that on Github.
      </p>
      <img src={nativeCountryNames} alt="World map of Internet domains" className="tipimg" />
    </Tip>
  );
}

export default LocalCountryNames;
