import ImageMagnifier from "../../common/ImageMagnifier";
import Separator from "../../common/Separator";
import { Card, Head, MapButton, Paragraph, Tip } from "../../common/TipsBuilder";
import TrainingModal from "../../common/TrainingModal";
import areaCodesMap from "../../../assets/img/fr/area-codes-map.png";

const phoneData: Card[] = [
  { front: `01 30`, back: `Yvelines, Val-d'Oise` },
  { front: `01 34`, back: `Yvelines, Val-d'Oise` },
  { front: `01 39`, back: `Yvelines, Val-d'Oise` },
  { front: `01 40`, back: `Paris` },
  { front: `01 41`, back: `Hauts-de-Seine, Val-d'Oise` },
  { front: `01 42`, back: `Paris, Hauts-de-Seine, Seine-Saint-Denis, Val-de-Marne` },
  { front: `01 43`, back: `Paris, Seine-Saint-Denis, Val-de-Marne` },
  { front: `01 44`, back: `Paris` },
  { front: `01 45`, back: `Paris, Val-de-Marne` },
  { front: `01 46`, back: `Paris, Essonne, Hauts-de-Seine, Val-de-Marne` },
  { front: `01 47`, back: `Paris, Hauts-de-Seine, Val-de-Marne` },
  { front: `01 48`, back: `Paris, Seine-Saint-Denis, Val-de-Marne, Val-d'Oise` },
  { front: `01 49`, back: `Paris, Hauts-de-Seine, Val-de-Marne` },
  { front: `01 53`, back: `Paris` },
  { front: `01 55`, back: `Paris, Hauts-de-Seine` },
  { front: `01 56`, back: `Paris, Val-de-Marne` },
  { front: `01 58`, back: `Paris` },
  { front: `01 60`, back: `Seine-et-Marne, Essonne` },
  { front: `01 64`, back: `Seine-et-Marne, Essonne` },
  { front: `01 69`, back: `Essonne, Seine-et-Marne` },
  { front: `01 70`, back: `Paris` },
  { front: `01 72`, back: `Paris, Seine-Saint-Denis` },
  { front: `01 73`, back: `Paris` },
  { front: `01 74`, back: `Paris` },
  { front: `01 75`, back: `Paris` },
  { front: `01 76`, back: `Paris, Hauts-de-Seine` },
  { front: `01 77`, back: `Paris` },
  { front: `01 78`, back: `Paris, Hauts-de-Seine` },
  { front: `01 79`, back: `Paris` },
  { front: `01 80`, back: `Paris` },
  { front: `01 81`, back: `Paris` },
  { front: `01 82`, back: `Paris` },
  { front: `01 83`, back: `Paris` },
  {
    front: `01 88`,
    back: `Paris, Seine-et-Marne, Yvelines, Essonne, Hauts-de-Seine, Seine-Saint-Denis, Val-de-Marne, Val-d'Oise`,
  },
  { front: `02 14`, back: `Calvados, Manche, Orne` },
  { front: `02 18`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 19`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 21`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 22`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 23`, back: `Ille-et-Vilaine` },
  { front: `02 28`, back: `Loire-Atlantique, Vendée` },
  { front: `02 29`, back: `Finistère` },
  { front: `02 30`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 31`, back: `Calvados` },
  { front: `02 32`, back: `Eure` },
  { front: `02 33`, back: `Manche, Orne` },
  { front: `02 34`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 35`, back: `Seine-Maritime` },
  { front: `02 36`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 37`, back: `Eure-et-Loir` },
  { front: `02 38`, back: `Loiret` },
  { front: `02 40`, back: `Loire-Atlantique` },
  { front: `02 41`, back: `Maine-et-Loire` },
  { front: `02 43`, back: `Mayenne, Sarthe` },
  { front: `02 44`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 45`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 46`, back: `Cher, Eure-et-Loir, Indre, Indre-et-Loire, Loir-et-Cher, Loiret` },
  { front: `02 47`, back: `Indre-et-Loire` },
  { front: `02 48`, back: `Cher` },
  { front: `02 49`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 50`, back: `Calvados, Manche, Orne` },
  { front: `02 51`, back: `Vendée, Loire-Atlantique` },
  { front: `02 52`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 53`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 54`, back: `Indre, Loir-et-Cher` },
  { front: `02 55`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 56`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 57`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 58`, back: `Calvados, Manche, Orne` },
  { front: `02 61`, back: `Calvados, Manche, Orne` },
  // { front: `02 62`, back: `La Réunion` },
  // { front: `02 63`, back: `La Réunion` },
  // { front: `02 69`, back: `Mayotte` },
  { front: `02 72`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 76`, back: `Eure, Seine-Maritime` },
  { front: `02 77`, back: `Eure, Seine-Maritime` },
  { front: `02 78`, back: `Eure, Seine-Maritime` },
  { front: `02 79`, back: `Eure, Seine-Maritime` },
  { front: `02 85`, back: `Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée` },
  { front: `02 90`, back: `Côtes-d'Armor, Finistère, Ille-et-Vilaine, Morbihan` },
  { front: `02 96`, back: `Côtes-d'Armor` },
  { front: `02 97`, back: `Morbihan` },
  { front: `02 98`, back: `Finistère` },
  { front: `02 99`, back: `Ille-et-Vilaine` },
  { front: `03 10`, back: `Ardennes, Aube, Marne, Haute-Marne` },
  { front: `03 20`, back: `centre of Nord` },
  { front: `03 21`, back: `Pas-de-Calais` },
  { front: `03 22`, back: `Somme` },
  { front: `03 23`, back: `Aisne` },
  { front: `03 24`, back: `Ardennes` },
  { front: `03 25`, back: `Aube, Haute-Marne` },
  { front: `03 26`, back: `Marne` },
  { front: `03 27`, back: `south of Nord` },
  { front: `03 28`, back: `north of Nord` },
  { front: `03 29`, back: `Meuse, Vosges` },
  { front: `03 39`, back: `Doubs, Jura, Haute-Saône, Territoire de Belfort` },
  { front: `03 44`, back: `Oise` },
  { front: `03 45`, back: `Côte-d'Or, Nièvre, Saône-et-Loire, Yonne` },
  { front: `03 51`, back: `Ardennes, Aube, Marne, Haute-Marne` },
  { front: `03 52`, back: `Ardennes, Aube, Marne, Haute-Marne` },
  { front: `03 53`, back: `Ardennes, Aube, Marne, Haute-Marne` },
  { front: `03 54`, back: `Meurthe-et-Moselle, Meuse, Moselle, Vosges` },
  { front: `03 55`, back: `Meurthe-et-Moselle, Meuse, Moselle, Vosges` },
  { front: `03 56`, back: `Meurthe-et-Moselle, Meuse, Moselle, Vosges` },
  { front: `03 57`, back: `Meurthe-et-Moselle, Meuse, Moselle, Vosges` },
  { front: `03 58`, back: `Côte-d'Or, Nièvre, Saône-et-Loire, Yonne` },
  { front: `03 59`, back: `Nord, Pas-de-Calais` },
  { front: `03 60`, back: `Aisne, Oise, Somme` },
  { front: `03 61`, back: `Nord, Pas-de-Calais` },
  { front: `03 62`, back: `Nord, Pas-de-Calais` },
  { front: `03 63`, back: `Doubs, Jura, Haute-Saône, Territoire de Belfort` },
  { front: `03 64`, back: `Aisne, Oise, Somme` },
  { front: `03 65`, back: `Aisne, Oise, Somme` },
  { front: `03 66`, back: `Nord, Pas-de-Calais` },
  { front: `03 67`, back: `Bas-Rhin, Haut-Rhin` },
  { front: `03 68`, back: `Bas-Rhin, Haut-Rhin` },
  { front: `03 69`, back: `Bas-Rhin, Haut-Rhin` },
  { front: `03 70`, back: `Doubs, Jura, Haute-Saône, Territoire de Belfort` },
  { front: `03 71`, back: `Côte-d'Or, Nièvre, Saône-et-Loire, Yonne` },
  { front: `03 72`, back: `Meurthe-et-Moselle, Meuse, Moselle, Vosges` },
  { front: `03 73`, back: `Côte-d'Or, Nièvre, Saône-et-Loire, Yonne` },
  { front: `03 75`, back: `Aisne, Oise, Somme` },
  { front: `03 76`, back: `Nord, Pas-de-Calais` },
  { front: `03 79`, back: `Côte-d'Or, Nièvre, Saône-et-Loire, Yonne` },
  { front: `03 80`, back: `Côte-d'Or` },
  { front: `03 81`, back: `Doubs` },
  { front: `03 82`, back: `Moselle, north of Meurthe-et-Moselle` },
  { front: `03 83`, back: `south of Meurthe-et-Moselle` },
  { front: `03 84`, back: `Jura, Haute-Saône, Territoire de Belfort` },
  { front: `03 85`, back: `north of Ain, Saône-et-Loire` },
  { front: `03 86`, back: `Yonne, Nièvre` },
  { front: `03 87`, back: `Moselle` },
  { front: `03 88`, back: `Bas-Rhin` },
  { front: `03 89`, back: `Haut-Rhin` },
  { front: `03 90`, back: `Bas-Rhin, Haut-Rhin` },
  { front: `03 92`, back: `Bas-Rhin` },
  { front: `04 11`, back: `Aude, Gard, Hérault, Lozère, Pyrénées-Orientales` },
  { front: `04 13`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Bouches-du-Rhône, Vaucluse` },
  { front: `04 15`, back: `Allier, Cantal, Haute-Loire, Puy-de-Dôme` },
  { front: `04 20`, back: `Corse-du-Sud, Haute-Corse` },
  { front: `04 22`, back: `Alpes-Maritimes, Var` },
  { front: `04 23`, back: `Alpes-Maritimes, Var` },
  { front: `04 26`, back: `Ain, Allier, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 27`, back: `Ain, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 30`, back: `Aude, Gard, Hérault, Lozère, Pyrénées-Orientales` },
  { front: `04 32`, back: `Bouches-du-Rhône, Vaucluse` },
  { front: `04 34`, back: `Aude, Gard, Hérault, Lozère, Pyrénées-Orientales` },
  { front: `04 37`, back: `Rhône` },
  { front: `04 38`, back: `Isère` },
  { front: `04 42`, back: `centre and east of Bouches-du-Rhône (Marseille excluded)` },
  { front: `04 43`, back: `Allier, Cantal, Haute-Loire, Puy-de-Dôme` },
  { front: `04 44`, back: `Allier, Cantal, Haute-Loire, Puy-de-Dôme` },
  { front: `04 48`, back: `Aude, Gard, Hérault, Lozère, Pyrénées-Orientales` },
  { front: `04 50`, back: `far north-east of Ain, Haute-Savoie` },
  { front: `04 56`, back: `Isère, Savoie, Haute-Savoie` },
  { front: `04 57`, back: `Isère, Savoie, Haute-Savoie` },
  { front: `04 58`, back: `Isère, Savoie, Haute-Savoie` },
  { front: `04 63`, back: `Allier, Cantal, Haute-Loire, Puy-de-Dôme` },
  { front: `04 65`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Bouches-du-Rhône, Vaucluse` },
  { front: `04 66`, back: `Gard, Lozère` },
  { front: `04 67`, back: `Gard, Hérault` },
  { front: `04 68`, back: `Aude, Pyrénées-Orientales` },
  { front: `04 69`, back: `Ain, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 70`, back: `Allier` },
  { front: `04 71`, back: `Cantal, Haute-Loire` },
  { front: `04 72`, back: `Lyon` },
  { front: `04 73`, back: `Puy-de-Dôme` },
  { front: `04 74`, back: `Ain, Rhône (Lyon excluded), north of Isère` },
  { front: `04 75`, back: `Ardèche, Drôme` },
  { front: `04 76`, back: `Isère` },
  { front: `04 77`, back: `Loire` },
  { front: `04 78`, back: `Lyon` },
  { front: `04 79`, back: `far east of Ain, Savoie` },
  { front: `04 80`, back: `Isère, Savoie, Haute-Savoie` },
  { front: `04 81`, back: `Ain, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 82`, back: `Ain, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 83`, back: `Alpes-Maritimes, Var` },
  { front: `04 84`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Bouches-du-Rhône, Vaucluse` },
  { front: `04 85`, back: `Isère, Savoie, Haute-Savoie` },
  { front: `04 86`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Bouches-du-Rhône, Vaucluse` },
  { front: `04 87`, back: `Ain, Ardèche, Drôme, Loire, Rhône` },
  { front: `04 88`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Bouches-du-Rhône, Vaucluse` },
  { front: `04 89`, back: `Alpes-Maritimes, Bouches-du-Rhône, Var` },
  { front: `04 90`, back: `west of Bouches-du-Rhône, Vaucluse` },
  { front: `04 91`, back: `Marseille` },
  { front: `04 92`, back: `Alpes-de-Haute-Provence, Hautes-Alpes, Alpes-Maritimes` },
  { front: `04 93`, back: `Alpes-Maritimes` },
  { front: `04 94`, back: `Var` },
  { front: `04 95`, back: `Corse-du-Sud, Haute-Corse` },
  { front: `04 96`, back: `Marseille` },
  { front: `04 97`, back: `Alpes-Maritimes` },
  { front: `04 98`, back: `Var` },
  { front: `04 99`, back: `Hérault` },
  // { front: `05 8`, back: `Saint-Pierre-et-Miquelon` },
  { front: `05 16`, back: `Charente, Charente-Maritime, Deux-Sèvres, Vienne` },
  { front: `05 17`, back: `Charente, Charente-Maritime, Deux-Sèvres, Vienne` },
  { front: `05 18`, back: `Corrèze, Creuse, Haute-Vienne` },
  { front: `05 19`, back: `Corrèze, Creuse, Haute-Vienne` },
  { front: `05 24`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 31`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 32`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 33`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 34`, back: `Haute-Garonne` },
  { front: `05 35`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 36`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 40`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 45`, back: `Charente` },
  { front: `05 46`, back: `Charente-Maritime` },
  { front: `05 47`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 49`, back: `Deux-Sèvres, Vienne` },
  { front: `05 53`, back: `Dordogne, Lot-et-Garonne` },
  { front: `05 54`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 55`, back: `Corrèze, Creuse, Haute-Vienne` },
  { front: `05 56`, back: `Gironde` },
  { front: `05 57`, back: `north of Gironde` },
  { front: `05 58`, back: `Landes` },
  { front: `05 59`, back: `Pyrénées-Atlantiques` },
  { front: `05 61`, back: `Ariège, Haute-Garonne` },
  { front: `05 62`, back: `Gers, Hautes-Pyrénées` },
  { front: `05 63`, back: `Tarn, Tarn-et-Garonne` },
  { front: `05 64`, back: `Dordogne, Gironde, Landes, Lot-et-Garonne, Pyrénées-Atlantiques` },
  { front: `05 65`, back: `Aveyron, Lot` },
  { front: `05 67`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 79`, back: `Charente, Charente-Maritime, Deux-Sèvres, Vienne` },
  { front: `05 81`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 82`, back: `Ariège, Aveyron, Haute-Garonne, Gers, Lot, Hautes-Pyrénées, Tarn, Tarn-et-Garonne` },
  { front: `05 86`, back: `Charente, Charente-Maritime, Deux-Sèvres, Vienne` },
  { front: `05 87`, back: `Corrèze, Creuse, Haute-Vienne` },
  // { front: `05 90`, back: `Guadeloupe, Saint-Barthélemy, Saint-Martin` },
  // { front: `05 94`, back: `Guyane` },
  // { front: `05 96`, back: `Martinique` },
];

function get2digits() {
  return Math.floor(Math.random() * 100)
    .toString()
    .padStart(2, "0");
}

function AreaCodesFR() {
  const cards = phoneData.map((card) => ({
    ...card,
    front: `${card.front} ${get2digits()} ${get2digits()} ${get2digits()}`,
  }));

  return (
    <Tip>
      <Head>
        <h1>Area Codes</h1>
        <Separator />
        <TrainingModal cards={cards} />
        <MapButton url="https://www.geoguessr.com/maps/6077c7517935970001ea36d9/play" />
      </Head>
      <Paragraph>
        A French phone number consists of <strong>10 digits</strong>, starting with a &apos;0&apos; when dialed within
        France. When calling from abroad, the country code +33 replaces the initial &apos;0&apos;.{" "}
        <strong>The first four digits</strong> of a French phone number give an indication of the geographical location.
        <br />
        <br />
        For instance, numbers beginning with &apos;01&apos; are for Paris and the Île-de-France region, &apos;02&apos;
        for the northwest, &apos;03&apos; for the northeast, &apos;04&apos; for the southeast, and &apos;05&apos; for
        the southwest.
        <br />
        <br />
        However, mobile phone numbers starting with &apos;06&apos; and &apos;07&apos; are not tied to specific regions
        and can be used anywhere in France. Additionally, numbers starting with &apos;09&apos; are often used for
        internet-based phone services (VoIP) and are also not geographically specific.
      </Paragraph>
      <ImageMagnifier src={areaCodesMap} alt="Map of France showing area codes" />
    </Tip>
  );
}

export default AreaCodesFR;
